name: Continuous Integration Laravel

on: 
  push:
        branches:
         - develop
         - feature/*
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Create Database
      run: mysql --user="root" --password="root" -e "CREATE DATABASE myrace character set UTF8mb4 collate utf8mb4_bin;"
    - name: Create Table
      run: mysql --user="root" --password="root" -e "CREATE TABLE settings (setting_ID int, keyword varchar(255), param1 varchar(10));"
    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Run Dusk Tests
      run: php artisan dusk